# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PLShopCart' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PLShopCart
	pod 'MJExtension'
   	pod 'Masonry'
	pod 'MBProgressHUD'
	
  target 'PLShopCartTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PLShopCartUITests' do
    # Pods for testing
  end

end
